#!/bin/bash
# Mirror Linux Mint package archive. Adapted from https://wiki.ubuntu.com/Mirrors/Scripts

RSYNCSOURCE=rsync://rsync-packages.linuxmint.com/packages/
BASEDIR=/media/mirror/linuxmint/packages/

fatal() {
  echo "$1"
  exit 1
}

if [ ! -d ${BASEDIR} ]; then
  fatal "${BASEDIR} does not exist ! Is the LXC mount ok ?"
fi

rsync --recursive --times --links --hard-links \
  --stats \
  --exclude "Packages*" --exclude "Sources*" \
  --exclude "Release*" --exclude "InRelease" \
  "${RSYNCSOURCE}" "${BASEDIR}" || fatal "First stage of sync failed."

rsync --recursive --times --links --hard-links \
  --stats --delete --delete-after \
  "${RSYNCSOURCE}" "${BASEDIR}" || fatal "Second stage of sync failed."
