#!/bin/bash -e
# Mirror Archlinux

RSYNCSOURCE=rsync://arch.mirrors.ionfish.org/archlinux/
BASEDIR=/media/mirror/archlinux/

fatal() {
  echo "$1"
  exit 1
}

if [ ! -d ${BASEDIR} ]; then
  fatal "${BASEDIR} does not exist ! Is the LXC mount ok ?"
fi

rsync -rtlvH --stats --delete-after --delay-updates --safe-links \
  "${RSYNCSOURCE}" "${BASEDIR}" || fatal "First stage of sync failed."

host=$(/bin/hostname -f)
date -u > "${BASEDIR}/project/trace/${host}" || exit 2
